### ISSUE TITLE
Remove Redis (make it optional)

### ISSUE THREAD

**Issue by maxpou** [maxpou/docker-symfony#12]
Hi everyone,

I'm planning to remove Redis. I don't want to integrate it natively.
Instead, I prefer make it optional.

TODO: 
- [x] Update [schema.pptx](https://github.com/maxpou/docker-symfony/files/483024/schema.pptx)
- [ ] Update docker-compose.yml
- [ ] Remove redis mention in readme.md
- [ ] Add/edit the custom.md file to explain how to add Redis in this stack

**Comment by maxpou** [comment]
Step 1: done.
[schema.pptx](https://github.com/maxpou/docker-symfony/files/580855/schema.pptx)

![symfony-docker](https://cloud.githubusercontent.com/assets/6160970/20140566/cbafaff4-a683-11e6-94d2-8d5280ed8172.png)

**Comment by stephanvierkant** [comment]
Great! Any plans on making ELK optional as well?

**Comment by maxpou** [comment]
@stephanvierkant for your information, I'm working on removing redis. Its almost already done.
Concerning ELK, can you open an other issue please?
