### ISSUE TITLE
Enable xdebug

### ISSUE THREAD

**Issue by meron1122** [maxpou/docker-symfony#14]
It would be great, if you add support for xdebug in php!

Regards

**Comment by meron1122** [comment]
Related; https://github.com/maxpou/docker-symfony/pull/15

**Comment by maxpou** [comment]
:+1:  good idea :-)
feel free to assign yourself!

**Comment by meron1122** [comment]
@maxpou  Related: #16

**Comment by maxpou** [comment]
(#16 merged)
