### ISSUE TITLE
mysqld: Can't create/write to file '/var/lib/mysql/is_writable' (Errcode: 13 - Permission denied)

### ISSUE THREAD

**Issue by aarongeiser** [maxpou/docker-symfony#19]
I am unable to get the MySQL container to work - the MySQL container produces the above error.

**Comment by maxpou** [comment]
Hi @aarongeiser,

Sorry man, I don't understand your problem.
What are you trying to do and why?

**Comment by aarongeiser** [comment]
Hi @maxpou -

I was simply following your instructions to run and use the docker-compose that you have included in this repository.

I discovered that - because I am on a mac - I had to add the following to the MySQL build:

RUN usermod -u 1000 mysql

and the following to the PHP and Nginx builds:

RUN usermod -u 1000 www-data

This alleviated the host permission issues I was getting.  Including the error that I posted in the issue.

**Comment by davidbonachera** [comment]
Same, i had to create a build for :
macOS Sierra 10.12.3, 
Docker Edge 17.04.0-ce,
Docker Compose 1.12  

Dockerfile : 
```Dockerfile
FROM mysql

RUN usermod -u 1000 mysql
```

Add to docker-compose : 
```Dockerfile
services:
    db:
        build: mysql
        volumes:
            - "./.data/api_db:/var/lib/mysql"
```

**Comment by Maels1991** [comment]
Same issue there, on macOS High Sierra.

Working solution : 

```
  db:
    volumes:
      - "db-data:/var/lib/mysql:rw"
```

**Comment by erlangparasu** [comment]
Thanks @davidbonachera @Maels1991
