### ISSUE TITLE
Xdebug is enabled but are we able to debug application using an IDE like phpStorm?

### ISSUE THREAD

**Issue by reypm** [maxpou/docker-symfony#20]
I was looking for a good Docker environment for develop Symfony2|3 apps and I think this one fit. :D I have seen that Xdebug is enabled but are we able to debug application using an IDE like phpStorm? Where is that documentation? If not I would like to contribute to this repository by adding that support and maybe continue improving it

**Comment by maxpou** [comment]
Hello @reypm ,

PR are welcome :)
This pull request can help you! #16 

Thanks, 
Maxpou

**Comment by reypm** [comment]
@maxpou ok, I will as soon as I have a time for test all of this but I think something is missing since the Xdebug should be listening on the host IP address in other words: `xdebug.remote_host = "<host_ip>"` and I am not seeing such line at any config files. Maybe I am wrong, the PR and the comments aren't helpful as well

**Comment by maxpou** [comment]
@meron1122 or @cuewizchris: do you have any idea?

**Comment by christianjungeFLA** [comment]
@reypm @maxpou This does work because we're using the `xdebug.remote_connect_back` setting. From the XDebug docs:

> If enabled, the xdebug.remote_host setting is ignored and Xdebug will try to connect to the client that made the HTTP request. It checks the $_SERVER['HTTP_X_FORWARDED_FOR'] and $_SERVER['REMOTE_ADDR'] variables to find out which IP address to use.

**Comment by cuewizchris** [comment]
@reypm @maxpou This does work because we're using the xdebug.remote_connect_back setting. From the XDebug docs:

If enabled, the xdebug.remote_host setting is ignored and Xdebug will try to connect to the client that made the HTTP request. It checks the $_SERVER['HTTP_X_FORWARDED_FOR'] and $_SERVER['REMOTE_ADDR'] variables to find out which IP address to use.

**Comment by reypm** [comment]
@cuewizchris thanks, didn't notice that before, closing this issue now, no PR needed
