### ISSUE TITLE
Can't access to symfony.dev

### ISSUE THREAD

**Issue by Stax** [maxpou/docker-symfony#21]
OS: macOS Sierra
Docker: 1.12.1
$ docker inspect --format '{{ .NetworkSettings.Networks.dockersymfony_default.IPAddress }}' $(docker ps -f name=nginx -q)
172.18.0.5

 $ cat /etc/hosts
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost 
172.18.0.5      symfony.dev

$ ping symfony.dev
PING symfony.dev (172.18.0.5): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6
^C
--- symfony.dev ping statistics ---
8 packets transmitted, 0 packets received, 100.0% packet loss`

$ docker-compose ps
dockersymfony_db_1      docker-entrypoint.sh mysqld      Up      0.0.0.0:3306->3306/tcp      
dockersymfony_elk_1     /usr/bin/supervisord -n -c ...   Up      0.0.0.0:81->80/tcp          
dockersymfony_nginx_1   nginx                            Up      443/tcp, 0.0.0.0:80->80/tcp 
dockersymfony_php_1     php-fpm                          Up      0.0.0.0:9000->9000/tcp      
dockersymfony_redis_1   docker-entrypoint.sh redis ...   Up      0.0.0.0:6379->6379/tcp

**Comment by maxpou** [comment]
I'm not sure, but I think I make a mistake in my README.md.
Run this command: `docker network inspect dockersymfony_default`

You will have something like that:
```json
[
    {
        "Name": "dockersymfony_default",
        "Id": "3ba9581afd9221ec53764fda00e7a7db0d284c7d341a21138f7dad487a52cf6b",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "07cb65206e849c22ed3e017f4e39c91e591b183cbba6c62b2d6dc1c96f9e1230": {
                "Name": "dockersymfony_db_1",
                "EndpointID": "3e18dfab826ea40db43cb54ecfe55d3cd9b364a4ceb0b460afe282f69fff325c",
                "MacAddress": "02:42:ac:13:00:02",
                "IPv4Address": "172.19.0.2/16",
                "IPv6Address": ""
            },
            "1a904a90219a19200f87556b1dd018301e5a879c7dc77c014a102321619ae12a": {
                "Name": "dockersymfony_nginx_1",
                "EndpointID": "4fb6d1ba581563ff42ca387921d1104b2967c1ca6b6c501778a21e2aac55d6df",
                "MacAddress": "02:42:ac:13:00:05",
                "IPv4Address": "172.19.0.5/16",
                "IPv6Address": ""
            },
            "597b06d48146812a521a48d4a3a4122553891f16e7f27a4ff2ebda90023b5a6e": {
                "Name": "dockersymfony_php_1",
                "EndpointID": "7806a45ecc32a317d874fcc52a3629b2f57c45463cfd6d3070400148ee2fedf7",
                "MacAddress": "02:42:ac:13:00:04",
                "IPv4Address": "172.19.0.4/16",
                "IPv6Address": ""
            },
            "72ba1cbb2c8bc25a86448d2c85fd641890f5558700348b78fdc4a565e519694a": {
                "Name": "dockersymfony_elk_1",
                "EndpointID": "3326f7278a33f5eb972906df3d5f55dd6b840ef9eb58d6af38e558508e1d3728",
                "MacAddress": "02:42:ac:13:00:06",
                "IPv4Address": "172.19.0.6/16",
                "IPv6Address": ""
            },
            "9e9bd1929c04c06ce0cbce68a8c8667cdcb7337b3957033e353216387a980f42": {
                "Name": "dockersymfony_redis_1",
                "EndpointID": "779abdfb849dd87bb0d0e941edc291e6db99974e9842ba87a61512d97b53ceb9",
                "MacAddress": "02:42:ac:13:00:03",
                "IPv4Address": "172.19.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

Now take the following value: IPAM > Config > Gateway and put it on your host file.
I'm not sure, but in your case, the address should be: 172.18.0.1

**Comment by Stax** [comment]
I changed my ip which was effectively 172.18.0.1. But I still can't access to it.
Host file: 

>stax$ cat /etc/hosts 
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost 
172.18.0.1      symfony.dev


Ping from local system output 

> stax$ ping 172.18.0.1
PING 172.18.0.1 (172.18.0.1): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6
Request timeout for icmp_seq 7
Request timeout for icmp_seq 8
--- 172.18.0.1 ping statistics ---
10 packets transmitted, 0 packets received, 100.0% packet loss

Ping from container 

> root@e0180f39d3c1:/var/www/symfony# ping symfony.dev
PING symfony.dev (172.18.0.1): 56 data bytes
64 bytes from 172.18.0.1: icmp_seq=0 ttl=64 time=0.721 ms
64 bytes from 172.18.0.1: icmp_seq=1 ttl=64 time=0.190 ms
64 bytes from 172.18.0.1: icmp_seq=2 ttl=64 time=0.183 ms
64 bytes from 172.18.0.1: icmp_seq=3 ttl=64 time=0.121 ms
64 bytes from 172.18.0.1: icmp_seq=4 ttl=64 time=0.123 ms
64 bytes from 172.18.0.1: icmp_seq=5 ttl=64 time=0.128 ms
64 bytes from 172.18.0.1: icmp_seq=6 ttl=64 time=0.130 ms
^C--- symfony.dev ping statistics ---
7 packets transmitted, 7 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.121/0.228/0.721/0.203 ms

**Comment by maxpou** [comment]
I'm wonder if your problem doesn't come from MacOS itself.
Did you read this: [https://docs.docker.com/docker-for-mac/networking/](https://docs.docker.com/docker-for-mac/networking/) ?

By the way, the [getting started](https://docs.docker.com/docker-for-mac/#explore) can run on your machine?

**Comment by Stax** [comment]
You were totaly right -> "Unfortunately, due to limitations in macOS, we’re unable to route traffic to containers, and from containers back to the host."
It's works now. Thanks for your time !

**Comment by maxpou** [comment]
You're welcome :)

**Comment by chandureddivari** [comment]
@Stax Can you please elaborate what did you change to make it work? Stuck with exactly same issue 😓

**Comment by Stax** [comment]
Sure ! [https://docs.docker.com/docker-for-mac/networking/](https://docs.docker.com/docker-for-mac/networking/) -> go to the section "I want to connect from a container to a service on the host",  I followed this. (sudo ifconfig lo0 alias 172.19.0.1/16)
Pay attention to the fact that mac os will erase this config when you update it.
