### ISSUE TITLE
Additonal configuration options

### ISSUE THREAD

**Issue by twify93** [maxpou/docker-symfony#27]
It's probably a good idea to have a env. option for the timezone.
Also it's good to make another branch or add option for PHP 7.1.

**Comment by twify93** [comment]
So I've tried just to change Dockerfile with php:7.1-fpm. The question is how can we add the option of choosing. I am pretty new to Docker.

**Comment by maxpou** [comment]
@twify93 : absolutely. If you want to choose another PHP version checkout the PHP docker hub: https://hub.docker.com/_/php/

Concerning environment file, I need to investigate. If someone else want to do it, he's welcome.

**Comment by twify93** [comment]
I will check the Environment stuff this weekend. Otherwise as I said, it works when you just switch the Dockerfile `FROM php:7.0-fpm` to `FROM php:7.1-fpm` and everything works out of the box.

**Comment by maxpou** [comment]
This is a solution: duplicate the Dockerfile and use the dockerfile option
 
```
services:
    php:
        build: php7-fpm
        dockerfile: Dockerfile-70
```


See doc: https://docs.docker.com/compose/compose-file/#/build

**Comment by twify93** [comment]
What should be the default PHP version? 7.0 or 7.1?
PS: This weekend you will receive the PR for the TZ.

**Comment by leroy0211** [comment]
You should tag a docker build. You can use different kind of approaches for this.

One approach is to add multiple folders for each version in your git repo, next you can tag a container build. This can be nice, but in my opinion this is too much to manage. 

The other approach is just to create a git tag for each docker build tag. For PHP 7.0 just create a git tag `7.0.0` (for each bugfix add 0.0.1; eg: `7.0.1`). And tag your docker build with `:latest` and the php version tag. 

When you want to add support for php 7.1, just create a branch, make everything compatible with 7.1. Create a git tag 7.1.0. And tag a docker build with `:latest` and the 7.1 php version.

So every time you tag a container build add the `:latest` so the latest is always the latest.

**Comment by maxpou** [comment]
Closing as we're using PHP 7.1 by default (since 280bfc3)
