### ISSUE TITLE
For smaller images, you could use alpine images instead of the debian images.

### ISSUE THREAD

**Issue by leroy0211** [maxpou/docker-symfony#36]
To have much less space, and much more quicker builds you could use alpine base images instead of the debian images. 

Keep in mind that some things are not possible, because alpine is very light weight!. 

Xdebug is one of them that might not be possible without a lot of extra packages. But when using multiple versions, you could create an alpine version of this stack for each php version.

**Comment by maxpou** [comment]
> Xdebug is one of them that might not be possible without a lot of extra packages.

Hi @leroy0211,
That exactly why I don't want Alpine image in this stack.

**Comment by leroy0211** [comment]
But why would you want xdebug in the stack? Or was the main purpose of this stack to be a development stack? 
The way I see it, is that a stack is production-ready. For development purposes you could add whatever you want.

**Comment by maxpou** [comment]
Because some people need XDebug. See #20 and #14 .

I see more this stack for development mode but I never wonder this question before. In fact, XDebug should be optional to satisfy dev and prod mode. So I prefer using Alpine when needed. Else, I'll use other official images.
