### ISSUE TITLE
Can't connect using symfony.dev

### ISSUE THREAD

**Issue by Bensji** [maxpou/docker-symfony#44]
Hi,

First of all, great package! Really love it.

I've followed all the steps, and everything works fine, except I can't connect to the server itself. (The connection just times out).

`docker network inspect bridge | grep Gateway` 
returns 172.17.0.1, so that looks fine.

But still, trying to connect to `symfony.dev or 172.17.0.1` is not possible.
I'm not running any proxies,... and I updated the hosts to include symfony.dev.

When running `docker network inspect bridge`
the containers don't show up under containers, shouldn't they be there?

**UPDATE:**
I have found that docker-compose makes it's own network (docker_default). This gateway is 172.20.0.1, and the containers are listed when I run `docker network inspect docker_default`, but I am not able to connect to that one either.

**UPDATE 2:**
If i go to localhost, I get served with the default nginx page. So, I'm guessing something is going wrong with the configuretion of the symfony part?

Thank you.

**Comment by maxpou** [comment]
Hi! 
Can you tell me what OS did you use? Linux or MacOS/Windows...
Do you have something interesting on yours logs? (`logs/nginx` and `logs/symfony`)

By the way, try to go on `symfony.dev/app_dev.php` entrypoint (you will have further more details). And also comment this part on this PHP file...

```php
// web/app_dev.php
if (isset($_SERVER['HTTP_CLIENT_IP'])
    || isset($_SERVER['HTTP_X_FORWARDED_FOR'])
    || !(in_array(@$_SERVER['REMOTE_ADDR'], array('127.0.0.1', 'fe80::1', '::1')) || php_sapi_name() === 'cli-server')
) {
    header('HTTP/1.0 403 Forbidden');
    exit('You are not allowed to access this file. Check '.basename(__FILE__).' for more information.');
}
```

**Comment by Bensji** [comment]
Hi,

Thank you for you comment.

I'm running MacOSX.
Docker version 1.13.0,

My logs are empty (This because I am not connecting to the server).

`$ docker network inspect docker_default
[
    {
        "Name": "docker_default",
        "Id": "68beb37aa62d5757513cc02c3ffa0ed4ce9d6bb21815fe3ef1d0cf2c3f9be03f",
        "Created": "2017-01-31T12:32:02.234790345Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.20.0.0/16",
                    "Gateway": "172.20.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Containers": {
            "3aa0cec73199d8612bc38618d623155f3d73ce60ac2b6c018510515e744b3611": {
                "Name": "docker_db_1",
                "EndpointID": "45f1cd7ef27ac9e32b53ed42a26d98f1347e2c005f4ac999b61fd3c886389927",
                "MacAddress": "02:42:ac:14:00:02",
                "IPv4Address": "172.20.0.2/16",
                "IPv6Address": ""
            },
            "6844dc23f15889051c0a5a639c22546db860ff9a902f877c760b94802bd84c0d": {
                "Name": "docker_php_1",
                "EndpointID": "10a715719b32b83d27067cefc4276a79d8ed3f505147d355acb4f43847eacd5a",
                "MacAddress": "02:42:ac:14:00:03",
                "IPv4Address": "172.20.0.3/16",
                "IPv6Address": ""
            },
            "bd1dc0dbc054cd06489f331e2405a65cfd9c978198a0c167d93dc172310d4b18": {
                "Name": "docker_elk_1",
                "EndpointID": "315a8a94226e462856da848daad6b1b1a8e53a21688f9c6720f6932ecc018a62",
                "MacAddress": "02:42:ac:14:00:05",
                "IPv4Address": "172.20.0.5/16",
                "IPv6Address": ""
            },
            "d77dcddd46c6ef05dcbeb2475081ca05fb35d2639d602420f3f02addcf751d2d": {
                "Name": "docker_nginx_1",
                "EndpointID": "3329cc43316f7bfa16d403a98ef9f44e7281db3b9d760fb96083c8e00956d8a9",
                "MacAddress": "02:42:ac:14:00:04",
                "IPv4Address": "172.20.0.4/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]`

And if I follow the documentation, this is the entire network inspect:

`$ docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "9948c8dbab87b4333ad8e41bef392c3af8e50d3f80a26a0c9c01c96b4a9371f4",
        "Created": "2017-01-31T15:16:21.94726503Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]`

I tried editing my /etc/hosts wit both the gateways, but without success.

**Comment by maxpou** [comment]
On the readme/ 

>   3. Update your system host file (add symfony.dev)
> 
>     ```bash
>     # UNIX only: get containers IP address and update host (replace IP according to your configuration)
>     $ docker network inspect bridge | grep Gateway
> 
>     # unix only (on Windows, edit C:\Windows\System32\drivers\etc\hosts)
>     $ sudo echo "171.17.0.1 symfony.dev" >> /etc/hosts
> 
>     ```
> **Note:** For **OS X**, please take a look [here](https://docs.docker.com/docker-for-mac/networking/) [...]

I wrote **UNIX only**. For MacOS, put this line in your hosts file:

```
127.0.0.1 symfony.dev
```

Let me know if it's ok!

**Comment by Bensji** [comment]
This works like a charm. Thank you for your help!
