### ISSUE TITLE
Extensions not installable ? 

### ISSUE THREAD

**Issue by Fabr9193** [maxpou/docker-symfony#47]
Hello!!

First of, that's a great job you did and it would definetley save me from using Wamp from windows.
I cloned my git repository inside the /var/www/symfony  and when i try to composer install it says that mcrypt is not found now the question as written above : how do I simply add an extension because every move i tried i had to install once again php7.0 from a different ppa

Thanks in advance.

Fabricio

**Comment by maxpou** [comment]
Hi!
Thanks!

If you want mcrypt, you need to update the Dockerfile under the PHP folder.


```dockerfile
FROM php:7.0-fpm
RUN apt-get update && apt-get install -y \
        libmcrypt-dev \
# ...
RUN docker-php-ext-install -j$(nproc) iconv mcrypt
```

See the official doc for further more information. 
https://github.com/docker-library/docs/tree/master/php#php-core-extensions

Cheers.

**Comment by Fabr9193** [comment]
Merci beaucoup ! 

Courage pour tout !

**Comment by maxpou** [comment]
You're welcome :)
