### ISSUE TITLE
Entering http://symfony.dev/ = ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by ktrzos** [maxpou/docker-symfony#52]
Done all by your instructions in README. Got `ERR_CONNECTION_TIMED_OUT` error while entering `http://symfony.dev` address. Don't know how to enter the project...

On `http://localhost` I'm getting "Welcome to nginx on Debian!" page.

ALSO, can't connect to my MySQL server via remote application like MySQL Workbench.
![screenshot_1](https://cloud.githubusercontent.com/assets/14212721/24585803/56cb570c-1793-11e7-9941-edc5ea3f4923.png)

(Windows 10 here)

**Comment by ktrzos** [comment]
Had to add

```yml
services:
    db:
        ports:
            - 3306:3306
```

And set `127.0.0.1 symfony.dev` in hosts (instead of `171.17.0.1 symfony.dev`).

**Comment by maxpou** [comment]
> And set 127.0.0.1 symfony.dev in hosts (instead of 171.17.0.1 symfony.dev).

You didn't read the note 😉
