### ISSUE TITLE
Permissions problem after every cache clearing

### ISSUE THREAD

**Issue by ktrzos** [maxpou/docker-symfony#54]
Hello again,

I've got problem in which after every `sf3 cache:clear` in `php` container I'm getting:

```
Cache directory "/var/www/site/var/cache/dev" is not writable.
```

When I set `chmod -R 777` on my cache directory (on host), everything is ok, but when I again use above cache clearing command, the problem is back. Do I really need to set permissions on each cache clearing? Any proposals what to add to `Dockerfile`?

**Comment by lierimelted** [comment]
@ktrzos , have you tried the official way to set up permissions at the host machine? http://symfony.com/doc/current/setup/file_permissions.html
Also, which group owns those files in var/ folder after cache cleared?

**Comment by ktrzos** [comment]
@lierimelted
I have not. Used it, and I see that it's working... for now.

```
$ HTTPDUSER=`ps axo user,comm | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1`

$ sudo setfacl -R -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX var
$ sudo setfacl -dR -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX var
```

I have these files in `var/` directory in `www-data` group.

**Comment by ktrzos** [comment]
After removing container and building again, permission problem occurred again...
And I can't event run those commands again:
`setfacl: Option -m: Invalid argument near character 3`
:D

**Comment by maxpou** [comment]
Sorry for the delay. I cannot reproduce on my side (I didn't get this problem since a while)
What happen when you add this line in your dockerfile?

```Dockerfile
RUN usermod -u 1000 www-data 
```

Then force rebuild with `docker-compose build --force-rm --no-cache --pull`

**Comment by qweluke** [comment]
the answer is simple. Clear cache without warmup.
ex.  `sf3 cache:clear --no-warmup`. That's all :)

**Comment by IvanAlekseevichPopov** [comment]
qweluke, problem the problem will not go away, if cache warmup in runtime. Need rights on files on UID, same as in host mashine, and php-fpm must run from user with this rights.

**Comment by Glideh** [comment]
```Dockerfile
RUN usermod -u 1000 www-data
```

Works for me but not ideal since the image have to be built especially for a host.
I guess we should use volumes, maybe it would deserve a small howto.

**Comment by Glideh** [comment]
@ktrzos did you find an acceptable alternative or did you just give up ?

**Comment by ktrzos** [comment]
@Glideh After some time of using Docker and Symfony, problem vanished. I've mostly been using solution given by @lierimelted (http://symfony.com/doc/current/setup/file_permissions.html) and it's working. I don't really know what was wrong earlier.

**Comment by idchlife** [comment]
Problems with symfony cache and logs folders are insane. I totally want stand behind phrase "gave up". But I can't since this is one of very few problems with Symfony
