### ISSUE TITLE
MySQL connection failed

### ISSUE THREAD

**Issue by alex-sorochkin** [maxpou/docker-symfony#59]
Hello!
I'm starting a new project using symfony and your containers. But I face with this error on establishing the MySQL connection: `SQLSTATE[HY000] [2002] Connection refused`

I googled this issue and they suggest to use `localhost` instead of `127.0.0.1` as a host. If I change this I get another error: `SQLSTATE[HY000] [2002] No such file or directory`.

I spent all the day trying to find the solution, but still no result. I tried all the combinations of hosts, ports, database name, also different usernames (root and user) - no result.

If I try to connest MySQL from command line - this works fine.

Not to have any config issues I was trying to create connection directly:
`$conn = new \PDO('mysql:dbname=mydb;host=localhost;charset=UTF8;unix_socket=/var/run/mysqld/mysqld.sock', 'user', 'userpass');` - so I'm sure this is just connection issue, but not a symfony problem. I just tried to use socket as the guys recommended in StackOverflow.

Do you have any ideas how to sort this?
Thanks, Alex.

**Comment by maxpou** [comment]
Hi @alex-sorochkin,
the host seems to be wrong. You cannot connect to 127.0.0.1 from another container.
In the [setup guide](https://github.com/maxpou/docker-symfony#installation), the step 4.1 indicate the correct host: `db` (instead of localhost/127.0.0.1)

cheers

**Comment by 11mb** [comment]
I have the same problem. The correct host is 'db' indeed, but in my case the database container isn't up. When I do a 'docker ps' I get only:

- elk
- nginx
- php

**Comment by alex-sorochkin** [comment]
Thanks a lot!!! It works now!
Seems I missed it during the installation, and forgot when returned again.

**Comment by maxpou** [comment]
Good news :wink: 

@11mb : please open another issue and don't forget to provide more details (i.e. configuration files, `docker info`...)

**Comment by 11mb** [comment]
Hi Maxpou, thx for your work on this repo and your feedback! I opened a new issue #60. I found a walk-around by using a volume in docker-compose.yml.
