### ISSUE TITLE
Can´t connect with websocket

### ISSUE THREAD

**Issue by n0ni0** [maxpou/docker-symfony#76]
Hi, im using this docker image with [WebSocketBundle]( https://github.com/GeniusesOfSymfony/WebSocketBundle) symfony works great, but i can´t connect from my local env with docker to connect with websocket.
var webSocket = WS.connect("ws://127.0.0.1:1337");

In local env without docker websocket work.
I need to change anything in dockerfile or modify nginx config?

Thx in advance.

**Comment by maxpou** [comment]
Hi,
You need to map your ports.
See: https://docs.docker.com/compose/compose-file/#ports

cheers

**Comment by n0ni0** [comment]
Hello again, ports are mapped but not connect

    nginx:
        build: nginx
        ports:
            - 80:80
            - 1337:1337
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx

**Comment by n0ni0** [comment]
Finally works.
- Map port in php container 
- Set ip of websocket server in config.yml to 0.0.0.0 instead of 127.0.0.1
Thank maxpow

**Comment by maxpou** [comment]
> Set ip of websocket server in config.yml to 0.0.0.0 instead of 127.0.0.1

oh you're using MacOS/Windows... that's probably why!

You're welcome :wink:

**Comment by benmarten** [comment]
>     * 0.0.0.0

Thanks, that solved my problem!
