### ISSUE TITLE
Symfony 3 problem with /cache, /logs permissions.

### ISSUE THREAD

**Issue by idchlife** [maxpou/docker-symfony#83]
Well, here goes again (not in this repo but in general)

As I understand this docker configuration for building symfony application heavily depending on files on host machine via volumes.

But, then comes the problem with permissions.

Ideal setup: logs, cache etc inside docker container and also just "mirrored" via volumes.
Actual problems come when Symfony tries to write and as I guess encounters permission denied to files on host folders, mirrored via volumes.
So there actually for every docker restart and symfony cache:clear should be additional instruction on host machine, like chmod and rm -rf old logs etc.

Is it even good approach for Symfony docker application to not have logs via volumes and expose volumes just to web/, app/, vendors/, src/ so assets symlinks would work for nginx container?

Also wondering, why nginx logs volumes do not have this problem :/

**Comment by maxpou** [comment]
Related #54

**Comment by maxpou** [comment]
Hey,

Did you try this solution?
https://github.com/maxpou/docker-symfony/issues/54#issuecomment-297479066

> Also wondering, why nginx logs volumes do not have this problem :/

Probably because it's the correct user
