### ISSUE TITLE
PHP 5.6 version

### ISSUE THREAD

**Issue by habibun** [maxpou/docker-symfony#93]
By default **docker-symfony** use 7.1 PHP version. Can I change PHP version 7.1 to 5.6

I am running Ubuntu 16.04.

**Comment by DeadPixelz01** [comment]
Within PHP's Dockerfile, you should just be able to change 'FROM php:7.1-fpm' to 'FROM php:5.6-fpm'.(see commit 3529253). Not 100% sure if anything else would need to be changed.

**Comment by habibun** [comment]
thanks, it works. the only problem was xdebug version, I changed this `RUN pecl install xdebug` to `RUN pecl install xdebug-2.5.5`
