### ISSUE TITLE
Nginx Bad Gateway

### ISSUE THREAD

**Issue by vialcollet** [maxpou/docker-symfony#95]
I am running a Sf2.8 application and try to have it setup on this docker-symfony stack using Windows 7.
I have solved directory sharing and changed the cache directory to solve usual issues.
Now when I access http://symfony.local, I have a 502 Bad Gateway.
Could you point me to the right direction?
Thanks

**Comment by isnnn** [comment]
Did you check the container logs for any errors?

``` 
docker-compose logs php
docker-compose logs nginx

**Comment by vialcollet** [comment]
I finally ended up migrating to sf 3.4. This is working now fine.
Thanks
