### ISSUE TITLE
SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client

### ISSUE THREAD

**Issue by truckee** [maxpou/docker-symfony#98]
On a Ubuntu 16 VM (w/ Windows host) I get 

> SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client

at the command `sf3 doctrine:database:create`

**Comment by Baskervilles** [comment]
Hi @truckee .
It seems to be due to mysql 8 forcing a new pwd format.

So in the _docker-compose.yml_ file, you have to replace `image: mysql` by `image: mysql:5.7` and run the `docker-compose build ` command.

**Comment by truckee** [comment]
Thanks! Makes a difference, but:

> /var/www/symfony# sf3 doctrine:database:create
> 15:06:59 ERROR     [console] Error thrown while running command "doctrine:databa                                                                             se:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Co                                                                             nnection timed out" ["error" => Doctrine\DBAL\Exception\ConnectionException { …}                                                                             ,"command" => "doctrine:database:create","message" => "An exception occurred in                                                                              driver: SQLSTATE[HY000] [2002] Connection timed out"] []

We're sneaking up on it I suppose.

**Comment by truckee** [comment]
FWIW, Symfony's `config.php`, both CLI & web (with localhost restriction removed), reports no fundamental issues. Just that `intl` extension, accelerator & short_tags should be added.

**Comment by truckee** [comment]
Figured it out! Original container creation created the `.data` directory & database. Changing from MySQL 8 to 5.7 did not recreate the data directory or the database. A stumper was that `sf3 doctrine:schema:create` also timed out.

The solution was to close the containers & remove the `./.data` directory and its contents. Brought the containers back up and was able to successfully do `sf3 doctrine:schema:create`.

Thanks for reading this far.

Off to the races!

**Comment by iamserkanyilmaz** [comment]
> Hi @truckee .
> It seems to be due to mysql 8 forcing a new pwd format.
> 
> So in the _docker-compose.yml_ file, you have to replace `image: mysql` by `image: mysql:5.7` and run the `docker-compose build ` command.

this worked thank you so much.
